In [7]:
y1 <- read.table("school1.dat")
y2 <- read.table("school2.dat")
y3 <- read.table("school3.dat")

   V1
1   2.11
2   9.75
3  13.88
4  11.30
5   8.93
6  15.66
7  16.38
8   4.54
9   8.86
10 11.94
11 12.47
12 11.11
13 11.65
14 14.53
15  9.61
16  7.38
17  3.34
18  9.06
19  9.45
20  5.98
21  7.44
22  8.50
23  1.55
24 11.45
25  9.73